# Создание массивов Numpy

In [2]:
import numpy as np

In [3]:
numbers =np.array([2,5,4,7,8,6,15])

In [4]:
type(numbers)

numpy.ndarray

In [5]:
numbers

array([ 2,  5,  4,  7,  8,  6, 15])

In [8]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
numbers.dtype

dtype('int64')

In [11]:
floats = np.array([0.0,0.1,0.2,0.3])

In [12]:
floats.dtype

dtype('float64')

## Операторы array

In [1]:
import numpy as np

In [2]:
num = np.arange(1,6)

In [4]:
num

array([1, 2, 3, 4, 5])

In [5]:
num*2

array([ 2,  4,  6,  8, 10])

In [6]:
num**3

array([  1,   8,  27,  64, 125])

In [7]:
num

array([1, 2, 3, 4, 5])

In [8]:
num += 10
num

array([11, 12, 13, 14, 15])

In [17]:
num1 = np.linspace(1.1,5,5)

num1

In [18]:
num1

array([1.1  , 2.075, 3.05 , 4.025, 5.   ])

In [19]:
num*num1

array([12.1 , 24.9 , 39.65, 56.35, 75.  ])

In [29]:
grades = np.full((4,3),np.random.randint(80,90))

In [32]:
for row in grades:
    for coul in range(len(row)):
        grades[row][coil] = np.random.randint(80,100)

IndexError: index 88 is out of bounds for axis 0 with size 4